baseURL = "https://kernelci.org/"

# -- languages --

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
contentDir = "content/en"
enableMissingTranslationPlaceholders = true # Useful when translating.

[languages]

[languages.en]
languageName ="English"
title = "KernelCI"
description = "The upstream Linux kernel test project"

# Sample additional language
#[languages.fr]
#languageName ="Français"
#title = "KernelCI"
#description = "Le projet upstream de test du noyau Linux"

# -- global site parameters --

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      style = "tango"

[params]
copyright = "KernelCI"
github_repo = "https://github.com/kernelci/kernelci-project"
github_branch = "main"
github_subdir = "kernelci.org"

[params.mermaid]
enable = true

# -- docsy parameters --

[params.ui]
sidebar_menu_compact = false
breadcrumb_disable = false
sidebar_search_disable = false
navbar_logo = true
footer_about_enable = true

[params.links]

[[params.links.user]]
  name ="Twitter"
  url = "https://twitter.com/kernelci"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news"

[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/kernelci"
  icon = "fab fa-github"
  desc = "Development takes place here!"

[[params.links.developer]]
  name = "Discord"
  url = "https://discord.gg/KWbrbWEyqb"
  icon = "fab fa-discord"
  desc = "Chat with other developers!"

# -- custom main menu --

[menu]
  [[menu.main]]
    identifier = "foundation"
    name = "Home"
    url = "https://kernelci.org"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://kernelci.org/blog/"
    weight = 2

  [[menu.main]]
    identifier = "kci-dev"
    name = "kci-dev cli"
    url = "https://kci.dev/"
    weight = 3

  [[menu.main]]
    identifier = "dashboard"
    name = "Web Dashboard"
    url = "https://dashboard.kernelci.org/"
    weight = 4

[[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/"
    weight = 5

# -- Hugo modules configuration --

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
